### ISSUE TITLE
500 Server Error

### ISSUE THREAD

**Issue by puiterwijk** [fedora-infra/mote#117]
With the recent change, we can now finally see the error that occurs at times.
After some time, Mote (might) gets into a state where all requests are answered with a Server Error, with the following message in the httpd error log:

````
2017-05-18 11:18:09,528 Exception on / [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/site-packages/mote/__init__.py", line 147, in index
    latest_meetings = get_cache_data('mote:latest_meetings')
  File "/usr/lib/python2.7/site-packages/mote/__init__.py", line 109, in get_cache_data
    res = util.get_json_cache(meeting_type)
  File "/usr/lib/python2.7/site-packages/mote/util.py", line 45, in get_json_cache
    cache = json.load(json_store)
  File "/usr/lib64/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 369, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 2184597 - line 1 column 2184599 (char 2184596 - 2184598)
````

**Comment by cydrobolt** [comment]
It seems like the error is being triggered by malformed JSON. Perhaps there are two sets of JSON data being loaded for some reason? 

Could this be due to some kind of race condition? I don't think mote itself is set to save multiple JSON elements into a single file. 

http://stackoverflow.com/questions/21058935/python-json-loads-shows-valueerror-extra-data

**Comment by copperii** [comment]
Is this issue still happening ?

**Comment by t0xic0der** [comment]
@copperii I'm not really sure about it.

Could you perform checks to see if the issue still persist?

**Comment by mscherer** [comment]
The issue still exist, and a patch is #248 

It seems the json is truncated when dumped so I suspect a race condition.

**Comment by mscherer** [comment]
Another solution would be to use memcached in production, and install it locally on the server. @darknao pointed me to #148 on that topic.
