### ISSUE TITLE
500 internal error for this releng meeting

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/mote#67]
I'm getting a 500 internal server error for this releng meeting:  https://meetbot.fedoraproject.org/fedora-meeting-1/2015-02-09/releng.2015-02-09-16.31

We get this traceback in the logs:

```python
ERROR:mote:Exception on /fedora-meeting-1/2015-02-09/releng.2015-02-09-16.31 [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/site-packages/mote/__init__.py", line 173, in catch_channel_logrequest
    group_name = m.group(1) # name of channel, e.g fedora-meeting
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by Cydrobolt** [comment]
Hmm. It looks like a regex error. 

Is that the link that MeetBot returned? It looks like it could potentially be an invalid link,  because it has no file name (generally .log.html or .html)

**Comment by Cydrobolt** [comment]
This seems to be the correct link (appended .html)


https://meetbot.fedoraproject.org/fedora-meeting-1/2015-02-09/releng.2015-02-09-16.31.html

**Comment by ralphbean** [comment]
Ah, I see.  We should probably return a 404 for it if possible instead of a 500.

**Comment by Cydrobolt** [comment]
Yeah

**Comment by Cydrobolt** [comment]
81aa8bb685762a91ffe310abd7a1a8910061ddaa should fix this issue. Thanks @ralphbean !
